#!/bin/bash
# ==========================================================================
# Platform 3 — 合规与应急响应平台 一键启动脚本
# 用法: bash init.sh [选项]
#
# 选项:
#   --reset         删除所有数据卷，全新初始化（会丢失数据）
#   --skip-init     只启动服务，不运行 init 容器
#   --secure        启用 ES/Kibana 认证（自动生成随机密码）
#   --monitor       附加部署 Prometheus + Grafana 监控栈
#   --backup        执行数据备份
#   --restore PATH  从指定备份路径恢复数据
#   --strict        严格模式，任一 init 失败则中止部署
#   --help          显示帮助
# ==========================================================================

set -e

# ---- Git Bash on Windows 路径转换保护 ----
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL="*"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
PROJECT_NAME="platform3"

# ---- 颜色输出 ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[init]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC} $1"; }
err()  { echo -e "${RED}[err]${NC}  $1"; }
info() { echo -e "${CYAN}[info]${NC} $1"; }

# ---- 参数解析 ----
RESET=false
SKIP_INIT=false
SECURE=false
MONITOR=false
BACKUP=false
RESTORE_PATH=""
STRICT_MODE=false
for arg in "$@"; do
  case "$arg" in
    --reset)          RESET=true ;;
    --skip-init)      SKIP_INIT=true ;;
    --secure)         SECURE=true ;;
    --monitor)        MONITOR=true ;;
    --backup)         BACKUP=true ;;
    --restore)        shift; RESTORE_PATH="$1" ;;
    --strict)         STRICT_MODE=true ;;
    --help)           echo "用法: bash init.sh [--reset] [--skip-init] [--secure] [--monitor] [--strict] [--backup] [--restore PATH]"; exit 0 ;;
    *)                err "未知参数: $arg"; exit 1 ;;
  esac
done

echo ""
echo "=============================================="
echo "  Platform 3 — 合规与应急响应平台 一键部署"
echo "=============================================="
echo ""

# ---- Step 0: 检查 Docker ----
log "Step 0: 检查 Docker 环境..."
if ! docker info >/dev/null 2>&1; then
  err "Docker 未运行，请先启动 Docker Desktop。"
  exit 1
fi
info "Docker $(docker version --format '{{.Server.Version}}')    Compose $(docker compose version --short 2>/dev/null || echo '?')"

# ---- Step 0.5: --reset 清理 ----
if $RESET; then
  warn "--reset: 删除所有数据卷和容器..."
  docker compose down -v 2>/dev/null || true
  log "已清理。"
fi

# ---- Step 0.6: --secure 密码生成 ----
if $SECURE; then
  log "Step 0.6: 启用安全模式，生成随机密码..."
  export ES_SECURITY_ENABLED=true

  if ! grep -q "^ELASTIC_PASSWORD=" .env 2>/dev/null || $RESET; then
    ELASTIC_PASSWORD=$(openssl rand -base64 24 2>/dev/null || cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
    KIBANA_ES_PASSWORD=$(openssl rand -base64 24 2>/dev/null || cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
    KIBANA_ENCRYPTION_KEY=$(openssl rand -base64 32 2>/dev/null || cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 43)
    {
      echo ""
      echo "# ---- Auto-generated by init.sh --secure ----"
      echo "ES_SECURITY_ENABLED=true"
      echo "ES_USER=elastic"
      echo "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      echo "KIBANA_ES_USER=kibana_system"
      echo "KIBANA_ES_PASSWORD=${KIBANA_ES_PASSWORD}"
      echo "KIBANA_ENCRYPTION_KEY=${KIBANA_ENCRYPTION_KEY}"
    } >> .env
    warn "密码已写入 .env 文件（请勿提交到 Git）"
  else
    warn ".env 中已存在 ELASTIC_PASSWORD，从 .env 加载现有密码..."
    export $(grep -E '^(ELASTIC_PASSWORD|KIBANA_ES_PASSWORD|KIBANA_ENCRYPTION_KEY|ES_USER|KIBANA_ES_USER|ES_SECURITY_ENABLED)=' .env | xargs)
  fi
else
  export ES_SECURITY_ENABLED=false
fi

# Export for docker compose (ensure they're set even if empty for non-secure mode)
export ES_SECURITY_ENABLED
export ELASTIC_PASSWORD="${ELASTIC_PASSWORD:-}"
export KIBANA_ES_PASSWORD="${KIBANA_ES_PASSWORD:-}"
export ES_USER="${ES_USER:-elastic}"
export KIBANA_ENCRYPTION_KEY="${KIBANA_ENCRYPTION_KEY:-platform3-kibana-demo-key-32chars}"

# ---- Step 0.7: --backup / --restore ----
if [ -n "$RESTORE_PATH" ]; then
  log "Step 0.7: 从 ${RESTORE_PATH} 恢复数据..."
  if [ -f scripts/restore.sh ]; then
    bash scripts/restore.sh "$RESTORE_PATH"
  else
    err "scripts/restore.sh 不存在"
  fi
  exit 0
fi

if $BACKUP; then
  log "Step 0.7: 执行备份..."
  if [ -f scripts/backup.sh ]; then
    bash scripts/backup.sh
  else
    err "scripts/backup.sh 不存在"
  fi
  exit 0
fi

# ---- Step 1: 生成证书 ----
log "Step 1: 生成 TLS 证书..."
if docker volume inspect "${PROJECT_NAME}_tls-data" >/dev/null 2>&1; then
  info "tls-data 卷已存在，跳过证书生成（若需重新生成请先 --reset）。"
else
  docker compose run --rm cert-init
  log "证书生成完毕。"
fi

# ---- Step 2: 启动所有服务 ----
if $MONITOR; then
  log "Step 2: 启动服务 + 监控栈 (docker compose up -d)..."
  docker compose -f docker-compose.yml -f docker-compose.monitoring.yml up -d
else
  log "Step 2: 启动服务 (docker compose up -d)..."
  docker compose up -d
fi

# ---- Step 3: 等待所有服务 healthy ----
log "Step 3: 等待服务就绪..."
SERVICES=(vault elasticsearch kibana)
MAX_WAIT=300
ELAPSED=0
INTERVAL=5

while [ $ELAPSED -lt $MAX_WAIT ]; do
  ALL_HEALTHY=true
  for svc in "${SERVICES[@]}"; do
    STATUS=$(docker inspect "platform3-${svc}" --format '{{.State.Health.Status}}' 2>/dev/null || echo "missing")
    if [ "$STATUS" != "healthy" ]; then
      ALL_HEALTHY=false
      break
    fi
  done

  if $ALL_HEALTHY; then
    log "全部 ${#SERVICES[@]} 个服务 healthy！(耗时 ${ELAPSED}s)"
    break
  fi

  echo -n "."
  sleep $INTERVAL
  ELAPSED=$((ELAPSED + INTERVAL))
done

if ! $ALL_HEALTHY; then
  echo ""
  warn "等待超时 (${MAX_WAIT}s)。当前状态:"
  docker compose ps
  echo ""
  warn "部分服务可能仍在启动中，可稍后手动检查: docker compose ps"
fi

echo ""

# ---- Step 4: 核心健康检查 ----
log "Step 4: 核心服务状态..."
docker compose ps --format "table {{.Service}}\t{{.Status}}\t{{.Ports}}"
echo ""

# ---- Step 5: 运行初始化 ----
if $SKIP_INIT; then
  info "--skip-init: 跳过初始化容器。"
else
  log "Step 5: 运行初始化容器..."

  run_init() {
    local name="$1"
    local logfile
    logfile="/tmp/init-${name}-$(date +%s).log"
    echo -n "  ${name}..."
    if docker compose run --rm "${name}" >"${logfile}" 2>&1; then
      echo -e " ${GREEN}OK${NC}"
      rm -f "${logfile}"
    else
      echo -e " ${RED}FAIL${NC} (日志: ${logfile})"
      echo -e "  ${YELLOW}最后 3 行:${NC}"
      tail -3 "${logfile}" 2>/dev/null | while read line; do echo "    $line"; done
      if ${STRICT_MODE:-false}; then
        err "严格模式: ${name} 失败，部署中止。"
        exit 1
      fi
    fi
  }

  run_init ilm-init
  run_init vault-init
  run_init kibana-init
  run_init dashboard-init
  echo ""
fi

# ---- Step 6: API 冒烟测试 ----
log "Step 6: API 冒烟测试..."

check_url() {
  local label="$1" url="$2"
  local code
  code=$(curl -sk -o /dev/null -w '%{http_code}' --connect-timeout 5 "$url" 2>/dev/null | tr -d '\r\n ' || echo "000")
  case "$code" in
    200|302|307|301|401) echo -e "  ${GREEN}[OK]${NC} ${label}  -> ${url} (${code})" ;;
    *)                  echo -e "  ${YELLOW}[??]${NC} ${label}  -> ${url} (${code})" ;;
  esac
}

check_url "Elasticsearch"   "http://localhost:19200"
check_url "Kibana"          "http://localhost:15601/api/status"
check_url "Vault"           "https://localhost:18200/v1/sys/health"

if $MONITOR; then
  check_url "Prometheus"     "http://localhost:9090"
  check_url "AlertManager"   "http://localhost:9093"
  check_url "Grafana"        "http://localhost:3000"
fi

echo ""

# ---- Step 7: 运行日志采集 ----
log "Step 7: 日志采集说明..."
echo ""
echo "  Platform 3 提供 5 个日志采集脚本，从各平台服务采集数据到 ES："
echo ""
echo "    docker compose run --rm -e ES_URL=http://host.docker.internal:19200 ingest-vault"
echo "    docker compose run --rm -e ES_URL=http://host.docker.internal:19200 ingest-minio"
echo "    docker compose run --rm -e ES_URL=http://host.docker.internal:19200 ingest-nifi"
echo "    docker compose run --rm -e ES_URL=http://host.docker.internal:19200 ingest-safeline"
echo "    docker compose run --rm -e ES_URL=http://host.docker.internal:19200 ingest-suricata"
echo ""
echo "  一键采集全部: bash scripts/ingest-all.sh"
echo ""

# ---- 完成 ----
echo "=============================================="
echo -e "  ${GREEN}部署完成！${NC}"
echo ""
echo "  门户地址:"
echo "    Kibana        http://localhost:15601"
echo "    Vault UI      https://localhost:18200"
echo "    Elasticsearch http://localhost:19200"
if $MONITOR; then
  echo "    Prometheus    http://localhost:9090"
  echo "    Grafana       http://localhost:3000"
fi
echo ""
echo "  凭证:"
echo "    Vault: Token 登录（运行 'docker compose logs vault-init' 查看）"
if $SECURE; then
  echo "    ES/Kibana: 见 .env 中 ELASTIC_PASSWORD"
fi
echo ""
echo "  数据采集:"
echo "    bash scripts/ingest-all.sh"
echo ""
echo "=============================================="
